import React from "react";
import { AuthorityBadge } from "./AuthorityBadge";

// Optional: rendered only when the /analyze response includes LLM advisory
// annotations (e.g. `llm_annotations`). The backend route does not return these
// by default, so this panel degrades gracefully to an explanatory empty state.

const styles = {
  note: {
    fontSize: 11,
    color: "#ec4899",
    background: "#ec489918",
    border: "1px solid #ec489955",
    borderRadius: 6,
    padding: "6px 8px",
    marginBottom: 10,
    lineHeight: 1.4,
  },
  item: {
    background: "#1a1f25",
    borderRadius: 6,
    padding: 9,
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 1.45,
  },
};

export default function LLMAdvisoryPanel({ annotations }) {
  const list = annotations || [];
  return (
    <div>
      <div style={styles.note}>
        <AuthorityBadge method="ml_llm" /> LLM output is <strong>advisory only</strong>
        {" "}and never overrides geometry, validation, or heuristic layers.
      </div>
      {list.length === 0 ? (
        <div style={{ opacity: 0.55, fontSize: 12, lineHeight: 1.5 }}>
          No LLM annotations in this response. When the optional LLM annotator is
          enabled, natural-language explanations appear here, clearly flagged as
          advisory.
        </div>
      ) : (
        list.map((a, i) => (
          <div key={i} style={styles.item}>
            <div style={{ fontFamily: "monospace", fontSize: 10, opacity: 0.55 }}>
              {a.feature_node_id}
            </div>
            <div style={{ marginTop: 3 }}>{a.natural_language}</div>
            {a.manufacturing_context && (
              <div style={{ marginTop: 4, opacity: 0.8 }}>{a.manufacturing_context}</div>
            )}
            <div style={{ marginTop: 5, fontSize: 10, opacity: 0.5, fontStyle: "italic" }}>
              {a.confidence_disclaimer ||
                "Generated by an LLM and advisory only."}
              {a.model_id ? ` · ${a.model_id}` : ""}
            </div>
          </div>
        ))
      )}
    </div>
  );
}
