"""API-layer adapter around the LLM semantic annotator.

The LLM is the LOWEST authority layer in OMIM (Authority Hierarchy Level 6 —
advisory only). Per Failure_Modes D-003, the LLM call path must degrade
gracefully: a missing API key, a network error, or a timeout must NEVER crash an
endpoint. The annotations it returns are labelled ``inference_method=ml_llm`` /
``authority_level=6`` and must NOT change geometry or validity.

This module wraps ``omim.semantic.llm_annotator.LLMAnnotator`` without modifying
it. The core annotator iterates ``mgg.feature_nodes()``, but the MGG builder
produces only geometry nodes (classification lives outside the graph). So here
we drive ``annotate_feature`` directly from the classifier's FeatureAnnotation
list, attaching the linked geometry data for context.
"""

from __future__ import annotations

import logging
from typing import Any

from omim.config import get_settings
from omim.graph.mgg import ManufacturingGeometryGraph
from omim.semantic.llm_annotator import LLMAnnotator
from omim.semantic.models import SemanticAnnotations

logger = logging.getLogger(__name__)

# Authority Hierarchy: LLM is Level 6, advisory only.
LLM_AUTHORITY_LEVEL = 6
LLM_INFERENCE_METHOD = "ml_llm"
ADVISORY_DISCLAIMER = (
    "Generated by an LLM (Authority Hierarchy Level 6). Advisory only — "
    "does NOT affect geometry, validation, or validity. Geometric and "
    "validation results remain authoritative."
)


def llm_configured() -> bool:
    """Return whether a Featherless API key is configured."""
    return bool(get_settings().featherless_api_key.strip())


def _unavailable_payload(note: str) -> dict[str, Any]:
    """Standard graceful-degradation payload when the LLM cannot run."""
    return {
        "llm_available": False,
        "authority_level": LLM_AUTHORITY_LEVEL,
        "inference_method": LLM_INFERENCE_METHOD,
        "advisory": True,
        "annotations": [],
        "note": note,
    }


async def annotate(
    mgg: ManufacturingGeometryGraph,
    annotations: SemanticAnnotations,
    *,
    max_features: int = 20,
    annotator: LLMAnnotator | None = None,
) -> dict[str, Any]:
    """Produce advisory LLM annotations for the classified features in *mgg*.

    Fully guarded: missing key / network error / timeout → graceful payload with
    ``llm_available`` reflecting whether the LLM was reachable. Never raises.

    The result NEVER carries geometry or validity changes; it is a pure overlay
    of natural-language explanations tagged as Level-6 advisory.
    """
    if not llm_configured():
        return _unavailable_payload(
            "No FEATHERLESS_API_KEY configured; LLM annotation skipped. "
            "Geometry and validation results are unaffected."
        )

    annotator = annotator or LLMAnnotator()

    # Index geometry node data so each feature can carry its source geometry.
    geom_by_id = {nid: data for nid, data in mgg.geometry_nodes()}

    # Only annotate features that were actually classified (skip UNKNOWN with
    # zero confidence — nothing meaningful for the LLM to explain).
    candidates = [
        fa
        for fa in annotations.feature_annotations
        if fa.feature_class != "UNKNOWN_FEATURE"
    ][:max_features]

    results: list[dict[str, Any]] = []
    any_error = False

    for fa in candidates:
        feature_data = {
            "node_id": fa.node_id,
            "feature_class": fa.feature_class,
            "confidence": fa.confidence,
            "evidence": fa.evidence,
        }
        geom_data = geom_by_id.get(fa.node_id)
        try:
            ann = await annotator.annotate_feature(feature_data, geom_data)
        except Exception:
            # D-003: any failure (network, timeout, auth, parse) is non-fatal.
            logger.exception("LLM annotation failed for %s", fa.node_id)
            any_error = True
            continue

        payload = ann.model_dump()
        # Stamp the advisory provenance explicitly so consumers cannot mistake
        # LLM output for an authoritative classification.
        payload["authority_level"] = LLM_AUTHORITY_LEVEL
        payload["inference_method"] = LLM_INFERENCE_METHOD
        payload["advisory"] = True
        payload["feature_class"] = fa.feature_class
        results.append(payload)

    note = ADVISORY_DISCLAIMER
    if any_error and not results:
        note = (
            "LLM was configured but every annotation call failed "
            "(network/timeout/upstream error). Degraded gracefully — geometry "
            "and validation results are unaffected."
        )

    return {
        "llm_available": True,
        "authority_level": LLM_AUTHORITY_LEVEL,
        "inference_method": LLM_INFERENCE_METHOD,
        "advisory": True,
        "annotations": results,
        "note": note,
    }
