"""Parser data models."""

from pydantic import BaseModel, Field


class RawEntity(BaseModel):
    """A single geometric entity extracted from a DXF file."""

    entity_id: str                  # UUID (generated by parser)
    ezdxf_handle: str = ""          # Original ezdxf entity handle (for provenance)
    entity_type: str                # "CIRCLE" | "LWPOLYLINE" | "ARC" | "LINE" | "SPLINE" | "POLYLINE"
    layer: str
    inferred_layer_type: str = "unknown"  # "cut" | "drill" | "pocket" | "engrave" | "border" | "unknown"

    coordinates: list               # Type-dependent (see spec)
    is_closed: bool | None = None

    # Derived (computed by Shapely at parse time)
    bounding_box: list[float] | None = None  # [xmin, ymin, xmax, ymax]
    centroid: list[float] | None = None      # [cx, cy]
    area_mm2: float | None = None
    perimeter_mm: float | None = None
    diameter_mm: float | None = None
    radius_mm: float | None = None

    is_approximated: bool = False    # True if SPLINE was approximated


class PanelBoundary(BaseModel):
    """Detected or inferred panel boundary."""

    entity_id: str
    coordinates: list
    bounding_box: list[float]
    area_mm2: float
    inferred: bool = False  # True if from bounding box, not explicit contour


class ParseWarning(BaseModel):
    """A non-fatal issue encountered during parsing."""

    warning_code: str
    message: str
    entity_id: str | None = None


class RawGeometry(BaseModel):
    """All geometry extracted from a single DXF file."""

    source_file: str
    source_file_hash: str
    dxf_version: str
    units_original: str = "mm"
    units_normalized_to: str = "mm"

    entities: list[RawEntity] = Field(default_factory=list)

    panel_boundary: PanelBoundary | None = None
    panel_boundary_inferred: bool = False

    entity_counts: dict[str, int] = Field(default_factory=dict)
    warnings: list[ParseWarning] = Field(default_factory=list)

    parse_timestamp: str = ""
    parser_version: str = "omim-v0.1.0"


class ParseError(BaseModel):
    """A fatal parsing error."""

    error_code: str  # "DXF_NOT_FOUND" | "DXF_CORRUPT" | "DXF_VERSION_UNSUPPORTED" | "DXF_TOO_LARGE"
    message: str
    recoverable: bool = False


class ParseResult(BaseModel):
    """Result of parsing a DXF file."""

    success: bool
    geometry: RawGeometry | None = None
    errors: list[ParseError] = Field(default_factory=list)
    warnings: list[ParseWarning] = Field(default_factory=list)
