"""Parser data models."""

from pydantic import BaseModel, Field

# Default layer-name prefix -> inferred operation type map (case-insensitive,
# prefix-matched). Exposed here so a ParserConfig can override it.
DEFAULT_LAYER_MAP: dict[str, list[str]] = {
    "cut": ["CUT", "CUT_", "PROFILE", "OUTLINE", "OUTER", "CONTOUR"],
    "drill": ["DRILL", "HOLE", "BORE", "PUNCH"],
    "pocket": ["POCKET", "GROOVE", "SLOT", "DADO", "RABBET"],
    "border": ["BORDER", "SHEET", "STOCK", "MATERIAL"],
    "engrave": ["ENGRAVE", "ETCH", "SCORE"],
}


class ParserConfig(BaseModel):
    """Tunable parser behaviour (see docs/03_INTERFACES/Parser_Interface.md)."""

    supported_dxf_versions: list[str] = Field(
        default_factory=lambda: [
            "AC1015", "AC1018", "AC1021", "AC1024", "AC1027", "AC1032",
        ]
    )
    max_file_size_bytes: int = 50 * 1024 * 1024  # 50MB
    target_units: str = "mm"
    layer_conventions: dict[str, list[str]] = Field(
        default_factory=lambda: {k: list(v) for k, v in DEFAULT_LAYER_MAP.items()}
    )
    # Number of segments used to approximate a SPLINE/ELLIPSE as a polyline.
    spline_approximation_segments: int = 50
    # Explode simple INSERT (block reference) entities into their primitives.
    explode_inserts: bool = True
    # Max INSERT nesting depth to explode (guards against pathological recursion).
    max_insert_depth: int = 5


class RawEntity(BaseModel):
    """A single geometric entity extracted from a DXF file."""

    entity_id: str                  # UUID (generated by parser)
    ezdxf_handle: str = ""          # Original ezdxf entity handle (for provenance)
    # entity_type: CIRCLE | LWPOLYLINE | ARC | LINE | SPLINE | POLYLINE
    entity_type: str
    layer: str
    # inferred_layer_type: cut | drill | pocket | engrave | border | unknown
    inferred_layer_type: str = "unknown"

    coordinates: list               # Type-dependent (see spec)
    is_closed: bool | None = None

    # Derived (computed by Shapely at parse time)
    bounding_box: list[float] | None = None  # [xmin, ymin, xmax, ymax]
    centroid: list[float] | None = None      # [cx, cy]
    area_mm2: float | None = None
    perimeter_mm: float | None = None
    diameter_mm: float | None = None
    radius_mm: float | None = None

    # Depth / 2.5D (see omim.parser.depth). depth_mm is None for pure-2D features
    # with no recoverable depth; depth_source records how it was obtained
    # ("z_elevation" = measured from 2.5D geometry, "layer_name" = inferred).
    depth_mm: float | None = None
    depth_source: str | None = None
    elevation_z: float | None = None  # raw entity Z (WCS), when present

    is_approximated: bool = False    # True if SPLINE was approximated


class PanelBoundary(BaseModel):
    """Detected or inferred panel boundary."""

    entity_id: str
    coordinates: list
    bounding_box: list[float]
    area_mm2: float
    inferred: bool = False  # True if from bounding box, not explicit contour


class ParseWarning(BaseModel):
    """A non-fatal issue encountered during parsing."""

    warning_code: str
    message: str
    entity_id: str | None = None


class RawGeometry(BaseModel):
    """All geometry extracted from a single DXF file."""

    source_file: str
    source_file_hash: str
    dxf_version: str
    units_original: str = "mm"
    units_normalized_to: str = "mm"

    entities: list[RawEntity] = Field(default_factory=list)

    panel_boundary: PanelBoundary | None = None
    panel_boundary_inferred: bool = False

    entity_counts: dict[str, int] = Field(default_factory=dict)
    warnings: list[ParseWarning] = Field(default_factory=list)

    parse_timestamp: str = ""
    parser_version: str = "omim-v0.1.0"


class ParseError(BaseModel):
    """A fatal parsing error."""

    error_code: str  # "DXF_NOT_FOUND" | "DXF_CORRUPT" | "DXF_VERSION_UNSUPPORTED" | "DXF_TOO_LARGE"
    message: str
    recoverable: bool = False


class ParseResult(BaseModel):
    """Result of parsing a DXF file."""

    success: bool
    geometry: RawGeometry | None = None
    errors: list[ParseError] = Field(default_factory=list)
    warnings: list[ParseWarning] = Field(default_factory=list)
