"""Semantic classification models — per 03_INTERFACES/Semantic_Interface.md."""

from __future__ import annotations

from pydantic import BaseModel, Field


class AlternativeHypothesis(BaseModel):
    """A candidate alternative feature classification."""

    feature_class: str
    confidence: float
    reason: str = ""


class FeatureAnnotation(BaseModel):
    """Classification result for a single geometry node."""

    node_id: str  # GeometryNode.node_id
    feature_class: str  # from Feature_Taxonomy
    confidence: float  # 0.0-1.0; reflects inference method ceiling
    evidence: list[dict] = Field(default_factory=list)  # EvidenceItem-like dicts
    provenance: dict | None = None  # ProvenanceRecord-like dict
    alternative_classes: list[AlternativeHypothesis] = Field(default_factory=list)


class OperationAnnotation(BaseModel):
    """Inferred CNC operation derived from feature classifications."""

    operation_type: str  # "DRILLING" | "CNC_ROUTING" | "PROFILE_CUTTING" | "NESTING"
    applies_to_node_ids: list[str] = Field(default_factory=list)
    confidence: float = 1.0
    provenance: dict | None = None  # ProvenanceRecord-like dict


class SemanticAnnotations(BaseModel):
    """Top-level output of the semantic classification layer.

    The semantic layer returns this object; it never mutates the MGG.
    """

    annotation_id: str
    graph_id: str
    timestamp: str = ""
    ontology_version: str = "v0.1.0"

    feature_annotations: list[FeatureAnnotation] = Field(default_factory=list)
    operation_annotations: list[OperationAnnotation] = Field(default_factory=list)

    coverage_ratio: float = 0.0  # fraction of GeometryNodes annotated
    unclassified_node_ids: list[str] = Field(default_factory=list)

    annotation_time_ms: float = 0.0


class SemanticAnnotation(BaseModel):
    """LLM-generated semantic explanation (advisory only)."""

    feature_node_id: str
    natural_language: str
    manufacturing_context: str = ""
    model_id: str = ""
    confidence_disclaimer: str = (
        "This annotation was generated by an LLM and is advisory only."
    )
