"""Semantic classification models."""

from __future__ import annotations

from pydantic import BaseModel, Field


class FeatureHypothesis(BaseModel):
    """A candidate feature classification with confidence score."""

    feature_class: str
    confidence: float
    reasoning: str = ""
    method: str = "deterministic"  # deterministic | heuristic | llm


class ClassificationResult(BaseModel):
    """Classification result for a single geometry node."""

    geometry_node_id: str
    best_hypothesis: FeatureHypothesis | None = None
    all_hypotheses: list[FeatureHypothesis] = Field(default_factory=list)


class SemanticAnnotation(BaseModel):
    """LLM-generated semantic explanation (advisory, never authoritative)."""

    feature_node_id: str
    natural_language: str
    manufacturing_context: str = ""
    model_id: str = ""
    confidence_disclaimer: str = (
        "This annotation was generated by an LLM and is advisory only. "
        "Geometric and validation data are authoritative."
    )
